# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170308_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorandum',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field'),
        ),
    ]
