# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_memorandum_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memoranda/'),
        ),
    ]
