# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170405_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petitions/'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='content',
            field=models.TextField(blank=True, help_text='Add the intro of the Memorandum.', null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='content',
            field=models.TextField(help_text='Explain the problem you want solved.'),
        ),
    ]
