# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 20:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170409_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add the intro of the Memorandum.', null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Explain the problem you want solved.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
