# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 11:38
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0001_initial'),
        ('posts', '0006_auto_20170411_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
