# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_petition_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Petition status'),
        ),
    ]
