# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_petition_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Draft'),
        ),
    ]
