# Generated by Django 3.1 on 2021-03-04 06:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('data', models.JSONField()),
                ('createdon', models.DateTimeField(default=datetime.datetime(2021, 3, 4, 9, 6, 20, 651352))),
            ],
        ),
        migrations.CreateModel(
            name='TimelineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='timeline/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelineimages', to='highlights.timeline')),
            ],
        ),
    ]
