# Generated by Django 3.1 on 2021-03-12 06:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeline',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 9, 0, 43, 100422)),
        ),
    ]
