# Generated by Django 3.1 on 2021-03-05 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 14, 1, 37, 1408)),
        ),
    ]
