# Generated by Django 3.1 on 2021-03-15 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_auto_20210312_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 14, 29, 44, 854393)),
        ),
    ]
