# Generated by Django 3.1 on 2021-03-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_auto_20210305_1401'),
        ('highlights', '0003_auto_20210315_1429'),
    ]

    operations = [
    ]
