version: '3'

volumes:
  production_postgres_data:
  production_postgres_backups:
  production_certbot_var:
  production_certbot_etc:

networks:
  dokeza:

services:
  nginx:
    container_name: nginx
    build:
      context: ./compose/production/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - production_certbot_var:/var/www/certbot
      - production_certbot_etc:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    networks:
      - dokeza

  certbot:
    container_name: certbot
    build:
      context: ./compose/production/certbot
      dockerfile: Dockerfile
    volumes:
      - production_certbot_var:/var/www/certbot
      - production_certbot_etc:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot -d dokeza.mzalendo.com -m admin@ra.co.ke,chanua@ra.co.ke -n --agree-tos --force-renewal --test-cert --dry-run
    networks:  
      - dokeza

  redis:
    container_name: redis
    build:
      context: ./compose/production/redis
      dockerfile: Dockerfile
    networks:
      - dokeza

  postgres:
    container_name: postgres
    build:
      context: ./compose/production/postgres
      dockerfile: Dockerfile
    image: dokeza_2_0_production_postgres
    env_file:
      - ./.envs/.production/.postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_backups:/backups
    networks:
      - dokeza

  # awscli:
  #   container_name: awscli
  #   build:
  #     context: ./compose/production
  #     dockerfile: awscli/Dockerfile
  #   env_file:
  #     - ./.envs/.production/.django
  #   volumes:
  #     - production_postgres_backups:/backups
  #   networks:
  #     - dokeza

  django: &django
    container_name: django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: dokeza_2_0_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - dokeza

  celeryworker:
    <<: *django
    image: dokeza_2_0_production_celeryworker
    command: /start-celeryworker
    networks:
      - dokeza

  celerybeat:
    <<: *django
    image: dokeza_2_0_production_celerybeat
    command: /start-celerybeat
    networks:
      - dokeza

  flower:
    <<: *django
    image: dokeza_2_0_production_flower
    command: /start-flower
    networks:
      - dokeza
