version: '3'

volumes:
  staging_postgres_data:
  staging_postgres_backups:
  staging_certbot_var:
  staging_certbot_etc:
  documentserver_postgresql_data:
  media:

networks:
  dokeza-network:
  ds-network:

services:
  postgres:
    container_name: postgres
    build:
      context: ./compose/production/postgres
      dockerfile: Dockerfile
    image: dokeza_2_0_staging_postgres
    env_file:
      - ./.envs/.production/.postgres
    volumes:
      - staging_postgres_data:/var/lib/postgresql/data
      - staging_postgres_backups:/backups
    networks:
      - dokeza-network

  nginx:
    container_name: nginx
    build:
      context: ./compose/production/nginx
      dockerfile: Dockerfile-staging
    restart: always
    volumes:
      - staging_certbot_var:/var/www/certbot
      - staging_certbot_etc:/etc/letsencrypt
      - media:/app/media/
    ports:
      - '80:80'
      - '443:443'
    networks:
      - dokeza-network

  certbot:
    container_name: certbot
    build:
      context: ./compose/production/certbot
      dockerfile: Dockerfile
    volumes:
      - staging_certbot_var:/var/www/certbot
      - staging_certbot_etc:/etc/letsencrypt
    command: certonly --cert-name staging-dokeza.mzalendo.com --webroot -w /var/www/certbot -d staging-dokeza.mzalendo.com, -m admin@ra.co.ke,chanua@ra.co.ke -n --agree-tos
    networks:  
      - dokeza-network

  redis:
    container_name: redis
    build:
      context: ./compose/production/redis
      dockerfile: Dockerfile
    networks:
      - dokeza-network

  django: &django
    container_name: django
    build:
      context: .
      dockerfile: ./compose/production/django-staging/Dockerfile
    image: dokeza_2_0_staging_django
    volumes:
      - media:/app/media/
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - dokeza-network

  trackerservice:
    build:
      context: ./tracker/reportservice
      dockerfile: Dockerfile
    image: dokeza_2_0_tracker_service
    container_name: trackerservice
    depends_on:
      - postgres
      - django
    restart: always
    networks:
      - dokeza-network

  documentserver:
    build:
      context: .
      dockerfile: ./compose/production/documentserver/Dockerfile-staging
    container_name: documentserver
    env_file:
      - ./.envs/.documentserver
    depends_on:
      - ds-postgresql
      - ds-rabbitmq
      - ds-redis
      - certbot
    ports:
      - '8082:80'
      - '8443:443'
    stdin_open: true
    restart: always
    volumes:
      - /var/www/onlyoffice/Data
      - /var/log/onlyoffice
      - /var/lib/onlyoffice/documentserver/App_Data/cache/files
      - /var/www/onlyoffice/documentserver-example/public/files
      - /usr/share/fonts
      - staging_certbot_etc:/etc/letsencrypt
    networks:
      - ds-network

  ds-rabbitmq:
    container_name: ds-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'
    networks:
      - ds-network

  ds-postgresql:
    container_name: ds-postgresql
    image: postgres:12.3-alpine
    env_file:
      - ./.envs/.documentserver
    restart: always
    expose:
      - '5432'
    volumes:
      - documentserver_postgresql_data:/var/lib/postgresql
    networks:
      - ds-network

  ds-redis:
    image: redis:5.0
    container_name: ds-redis
    restart: always
    networks:
      - ds-network

  celeryworker:
    <<: *django
    container_name: celeryworker
    image: dokeza_2_0_staging_celeryworker
    command: /start-celeryworker
    networks:
      - dokeza-network

  celerybeat:
    <<: *django
    container_name: celerybeat
    image: dokeza_2_0_staging_celerybeat
    command: /start-celerybeat
    networks:
      - dokeza-network

  flower:
    <<: *django
    container_name: flower
    image: dokeza_2_0_staging_flower
    command: /start-flower
    networks:
      - dokeza-network
