# Generated by Django 3.1 on 2020-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_participation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicevent',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bill: Open for Memoranda'), (2, 'Bill: In Committee'), (3, 'Bill: Plenary Session'), (4, 'Public Participation Meeting')], default=1, null=True, verbose_name='Event Agenda'),
        ),
    ]
