# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_auto_20170329_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='tags',
        ),
    ]
