# Generated by Django 3.0.9 on 2020-08-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='body',
        ),
    ]
