# Generated by Django 3.1 on 2020-11-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_bill_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='pdf',
            new_name='word_doc',
        ),
    ]
