# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20170308_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='law_reference',
            field=models.URLField(blank=True, help_text='This should be a link to the Kenya Law Review repository of the bill.', null=True),
        ),
    ]
