# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_bill_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_pic',
            field=models.ImageField(blank=True, help_text='Upload an image of the top stamped page of the bill.', null=True, upload_to='bill_pics/'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pdf',
            field=models.FileField(blank=True, help_text='Upload the actual bill here.', null=True, upload_to='bills/'),
        ),
    ]
