# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20170423_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='private',
            field=models.BooleanField(default=True, help_text='Please click to to make it public.'),
        ),
    ]
