# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-16 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_auto_20170602_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open for Memoranda'), (2, 'In Committee'), (3, 'Plenary Session'), (4, 'Commentary Closed')], default=1, verbose_name='Bill Stage'),
        ),
    ]
