# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-02 21:44
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('idea_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Submit Bill Opinion'), (2, 'Submit Petition'), (3, 'Submit Memorandum ')], default=1, null=True, verbose_name='Idea Type')),
                ('content', ckeditor.fields.RichTextField(help_text='What do you have in mind?')),
                ('draft', models.BooleanField(default=True, verbose_name='Draft')),
                ('publish', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-publish'],
                'verbose_name': 'idea',
                'verbose_name_plural': 'ideas',
            },
        ),
    ]
