# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedidea',
            name='submit_to',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'National Assembly'), (2, 'Senate')], default=1, null=True, verbose_name='Submit to'),
        ),
        migrations.AlterField(
            model_name='submittedidea',
            name='idea_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bill Opinion'), (2, 'Petition'), (3, 'Memorandum ')], default=1, null=True, verbose_name='Idea Type'),
        ),
    ]
