# Generated by Django 3.1 on 2021-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_subscribed_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed_tracker',
            field=models.BooleanField(default=False, verbose_name='Subscribe to monthly Bill Tracking?'),
        ),
    ]
