# Generated by Django 3.0.8 on 2020-07-08 09:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('users', '0002_auto_20200708_1257'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A document for discussion', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('purpose', models.TextField(blank=True, max_length=500, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, help_text='Copy the document and paste with all its styling. If necessary use the editing tools to style it sufficiently.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pdf', models.FileField(blank=True, help_text='Upload the actual document here if necessary.', null=True, upload_to='Documents/')),
                ('doc_pic', models.ImageField(blank=True, help_text='Upload an image of the top page of the document.', null=True, upload_to='doc_pics/')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Institution')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            bases=(hitcount.models.HitCountMixin, models.Model),
        ),
    ]
