# Generated by Django 3.1 on 2020-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='regulation',
            field=models.BooleanField(default=True, help_text='Uncheck if the document is not a regulation'),
        ),
    ]
