# Generated by Django 3.1.3 on 2020-12-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
            ],
            options={
                'db_table': 'bills_bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.bill')),
            ],
        ),
    ]
