# Generated by Django 3.1.3 on 2020-12-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20201204_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billtracker',
            options={'ordering': ['-pub_date']},
        ),
    ]
