# Generated by Django 3.1.3 on 2020-12-14 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20201214_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billtracker',
            options={'ordering': ['-stage_date']},
        ),
        migrations.RenameField(
            model_name='billtracker',
            old_name='description',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='billtracker',
            old_name='pub_date',
            new_name='stage_date',
        ),
        migrations.AddField(
            model_name='billtracker',
            name='stage',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
