# Generated by Django 3.1 on 2020-12-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20201214_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
            ],
            options={
                'db_table': 'bills_bill',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='billtracker',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.mybill'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
