# Generated by Django 3.1 on 2020-12-24 08:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0006_auto_20201222_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtracker',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billtracker',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 11, 13, 0, 711204)),
        ),
    ]
