# Generated by Django 3.1 on 2021-01-11 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20201224_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtracker',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 5, 31, 4, 898899)),
        ),
    ]
