# Generated by Django 3.1 on 2021-01-19 11:30

import datetime
from django.db import migrations, models
import uuid
from tracker.models import BillTracker

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20201224_1113'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in BillTracker.objects.all():
            row.uuid = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='billtracker',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=True,
        ),
        
        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='billtracker',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),

        # migrations.AlterField(
        #     model_name='billtracker',
        #     name='createdon',
        #     field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 14, 30, 20, 365507)),
        # ),
    ]
