# Generated by Django 3.1 on 2021-01-13 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210111_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtracker',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 9, 58, 45, 463721)),
        ),
    ]
