# Generated by Django 3.1 on 2021-01-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20210113_0958'),
        ('tracker', '0008_auto_20210119_1430'),
    ]

    operations = [
    ]
